services:
  spring:
    build: .
    container_name: spring
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app
    restart: unless-stopped
  
  postgres:
    image: postgres:14-bookworm
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_DB: "bank"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - app
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app
    restart: unless-stopped

networks:
  app: